apiVersion: v1
kind: Service
metadata:
  name: {{ include "rc-homework.fullname" . }}
  namespace: homework
  labels:
    {{- include "rc-homework.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.sourcePort }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: http
  selector:
    {{- include "rc-homework.selectorLabels" . | nindent 4 }}
